version: '3.0'
services:
  database-mssql:
    build: .
    image: vinnyfs89/mssql:1.0.0
    container_name: mssql
    volumes:
      # - docker-data:/var/opt/mssql # for mac
      - ./database/docker-data:/var/opt/mssql # for linux
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=root@Abcd11
      - MSSQL_PID=Developer
      #- RESTAURAR_BACKUP=true
